#ifndef CONFIG_USER_H
#define CONFIG_USER_H
#endif

#define LAYER_STATE_8BIT
#define DISABLE_RGB_MATRIX_DIGITAL_RAIN
#define DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_RAINDROPS
#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define TAPPING_TERM 150
#define QUICK_TAPPING_TERM 100
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 30
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 5
