#ifndef CONFIG_USER_H
#define CONFIG_USER_H
#endif

#define ORYX_CONFIGURATOR
#define DISABLE_RGB_MATRIX_DIGITAL_RAIN
#define DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_RAINDROPS

#include "../../config.h"

#undef TAPPING_TERM
#define TAPPING_TERM 120
#undef QUICK_TAPPING_TERM
#define QUICK_TAPPING_TERM 75
#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 30
#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 5
