#ifndef CONFIG_USER_H
#define CONFIG_USER_H
#endif

#define ORYX_CONFIGURATOR
#define DISABLE_RGB_MATRIX_DIGITAL_RAIN
#define DISABLE_RGB_MATRIX_ALPHAS_MODS
#define DISABLE_RGB_MATRIX_JELLYBEAN_RAINDROPS
#define DISABLE_RGB_MATRIX_RAINDROPS

#include "../../config.h"
